---
- name: "add ansible_user to docker users"
  become: yes
  user:
    name: "{{ ansible_user_id }}"
    groups: "docker"
    append: yes

- name: "pull jenkins lts"
  become: yes
  docker_image:
    name: "jenkinsci/jenkins:lts"


- name: "ensure jenkins configuration directories"
  become: yes
  file:
    name: "{{ item }}"
    owner: 1000
    group: 1000
    state: "directory"
  with_items:
    - "/etc/jenkins/ref"
    - "/etc/jenkins/config"

- name: "template in groovy scripts"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 1000
    group: 1000
  with_items:
    - src: "config.xml.j2"
      dest: "/etc/jenkins/config/config.xml"
    - src: "github-plugin-configuration.xml.j2"
      dest: "/etc/jenkins/config/github-plugin-configuration.xml"
    - src: "users_and_creds.groovy.j2"
      dest: "/etc/jenkins/ref/users_and_creds.groovy"

- name: "copy in simple groovy scripts"
  become: yes
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 1000
    group: 1000
  with_items:
    - src: "tcp-slave-agent-port.groovy"
      dest: "/etc/jenkins/ref/tcp-slave-agent-port.groovy"
    - src: "enable_slave_master_security.groovy"
      dest: "/etc/jenkins/ref/enable_slave_master_security.groovy"

- name: "get compose suite"
  become: yes
  git:
    accept_hostkey: yes
    depth: 1
    dest: "/opt/docker_jenkins_suite"
    repo: "https://github.com/sean-abbott/docker_jenkins_suite.git"

- name: "template in environment"
  become: yes
  template:
    src: "docker_jenkins_suite_.env.j2"
    dest: "/opt/docker_jenkins_suite/.env"

- name: "template in xml configs"
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: 1000
    group: 1000
  with_items:
    - src: "config.xml.j2"
      dest: "/opt/docker_jenkins_suite/jenkins/config/config.xml"
    - src: "github-plugin-configuration.xml.j2"
      dest: "/opt/docker_jenkins_suite/jenkins/config/github-plugin-configuration.xml"
    - src: "jenkins.model.JenkinsLocationConfiguration.xml.j2"
      dest: "/opt/docker_jenkins_suite/jenkins/config/jenkins.model.JenkinsLocationConfiguration.xml"
    - src: "hudson.plugins.git.GitSCM.xml.j2"
      dest: "/opt/docker_jenkins_suite/jenkins/config/hudson.plugins.git.GitSCM.xml"

- name: "set id_rsa contents"
  become: yes
  copy:
    content: "{{ jenkins_user_ssh_credential.private }}"
    dest: "/opt/docker_jenkins_suite/jenkins/config/id_rsa"
    owner: 1000
    group: 1000
    mode: 0600

- name: "set id_rsa.pub contents"
  become: yes
  copy:
    content: "{{ jenkins_user_ssh_credential.public }}"
    dest: "/opt/docker_jenkins_suite/jenkins/config/id_rsa.pub"
    owner: 1000
    group: 1000

- name: "copy in plugins.txt"
  become: yes
  copy:
    src: plugins.txt
    dest: "/opt/docker_jenkins_suite/jenkins/config/plugins.txt"
    owner: 1000
    group: 1000

- name: "start jenkins"
  become: yes
  docker_service:
    project_src: "/opt/docker_jenkins_suite"
    state: "present"
  register: jenkins_suite

- name: "debug jenkins_suite"
  debug:
    var: jenkins_suite
    verbosity: 1
